 const productos = [
 {
    id: 1,
    nombre: "Aparador Uspallata",
    imagen: "img/Kit de imágenes/aparador_uspallata.png",
    descripcion: "Aparador de seis puertas fabricado en nogal sostenible con tiradores metálicos en acabado latón. Su silueta minimalista realza el veteado natural de la madera, creando una pieza que combina funcionalidad y elegancia atemporal para espacios contemporáneos.",
    medidas: "180 × 45 × 75 cm",
    materiales: "Nogal macizo FSC®, herrajes de latón",
    acabado: "Aceite natural ecológico",
    peso: "68 kg",
    capacidad: "6 compartimientos interiores"
  },
  {
    id:2,
    nombre: "Biblioteca Recoleta",
    imagen: "img/Kit de imágenes/biblioteca_recoleta.png",
    descripcion: "Sistema modular de estantes abierto que combina estructura de acero Sage Green y repisas en roble claro. Perfecta para colecciones y objetos de diseño, su diseño versátil se adapta a cualquier espacio contemporáneo con elegancia funcional.",
    medidas: "100 × 35 × 200 cm",
    materiales: "Estructura de acero Sage Green, estantes de roble",
    acabado: "Laca mate ecológica",
    capacidad: "45kg por estante",
    modulares: "5 estantes ajustables"
  },
  {
    id:3,
    nombre: "Butaca Mendoza",
    imagen: "img/Kit de imágenes/butaca_mendoza.png",
    descripcion: "Butaca tapizada en bouclé Dusty Rose con base de madera de guatambú. El respaldo curvo abraza el cuerpo y ofrece máximo confort, mientras que su diseño orgánico aporta calidez y sofisticación a cualquier ambiente contemporáneo.",
    medidas: "80 × 75 × 85 cm",
    materiales: "Guatambú macizo, tela bouclée",
    acabado: "Cera vegetal, tapizado premium",
    tapizado: "Repelente al agua y manchas", 
    confort: "Espuma de alta densidad",
  },
  {
    id:4,
    nombre: "Sillón Copacabana",
    imagen: "img/Kit de imágenes/sillon_copacabana.png",
    descripcion: "Sillón lounge en cuero cognac con base giratoria en cero Burnt Sienna. Inspirado en la estética brasilera moderna de los 60, combina comodidad excepcional conun diseño icónico que trasciende tendencias y épocas",
    medidas: "90 × 85 × 95 cm",
    materiales: "Estructura de acero, cuero premium",
    acabado: "Cera vegetal, cuero teñido a mano",
    rotacion: "360° silenciosa y suave",
    garantia: "10 años en estructura",
  },        
  {
    id:5,
    nombre: "Mesa de Centro Araucaria",
    imagen: "img/Kit de imágenes/mesa_centro_araucaria.png",
    descripcion: "Mesa de centro con sobre circular de mármol Patagonia y base de tres patas en madera de nogal. Su diseño minimalista se convierte en el punto focal perfecto para cualquier sala de estar contemporánea, combinando la frialdad del mármol con la calidez de la madera.",
    medidas: "90 × 90 × 45 cm",
    materiales: "Sobre de mármol Patagonia, patas de nogal",
    acabado: "Mármol pulido, aceite natural en madera",  
    peso: "25 kg",
    carga_maxima: "25 kg distribuidos",
  },
  {
    id:6,
    nombre: "Mesa de Noche Aconcagua",
    imagen: "img/Kit de imágenes/mesa_noche_aconcagua.png",
    descripcion: "Mesa de noche con cajón oculto y repisa inferior en roble certificado FSC®. Su diseño limpio y funcional permite convivir con diferentes estilos de dormitorio, ofreciendo almacenamiento discreto y elegante para objetos personales.",
    medidas: "45 × 35 × 60 cm",
    materiales: "Roble macizo FSC®, herrajes soft-close",
    acabado: "Barniz mate de poliuretano",
    almacenamiento: "1 cajón + repisa inferior",
    características: "Cajón con cierre suave",
  },
  {
    id:7,
    nombre: "Sofá Patagonia",
    imagen: "img/Kit de imágenes/sofa_patagonia.png",
    descripcion: "Sofá de tres cuerpos tapizado en lino Warm Alabaster con patas cónicas de madera. Los cojines combinan espuma de alta resiliencia con plumón reciclado, ofreciendo comodidad duradera y sostenible para el hogar moderno",
    medidas: "220 × 90 × 80 cm",
    estructura: "Madera de eucalipto certificada FSC®",
    tapizado: "Lino 100% natural premium",
    relleno: "Espuma HR + plumón reciclado",
    sostenibilidad: "Materiales 100%reciclables",
  },
  {
    id:8,
    nombre: "Mesa Comedor Pampa",
    imagen: "img/Kit de imágenes/mesa_comedor_pampa.png",
    descripcion: "Mesa extensible de roble macizo con tablero biselado y sistema de apertura suave. Su diseño robusto y elegante se adapta perfectamente a reuniones íntimas o grandes celebraciones familiares, extendiéndose de 6 a 10 comensales.",
    medidas: "160-240 × 90 × 75 cm",
    materiales: "Roble macizo FSC®, mecanismo alemán",
    acabado: "Aceite-cera natural",
    capacidad: "6-10 comensales",
    extensión: "Sistema de mariposa central",
  },
  {
    id:9,
    nombre: "Sillas Córdoba",
    imagen: "img/Kit de imágenes/sillas_cordoba.png",
    descripcion: "Set de cuatro sillas apilables en contrachapado moldeado de nogal y estructura tubular pintada en Sage Green. Su diseño ergonómico y materiales de calidad garantizan comodidad y durabilidad en el uso diario, perfectas para comedores contemporáneos.",
    medidas: "45 × 52 × 80 cm",
    materiales: "Contrachapado nogal, tubo de acero",
    acabado: "Laca mate, pintura epoxi",
    apilalables: "Hasta 6 sillas",
    incluye: "Set de 4 sillas",
  },
  {
    id:10,
    nombre: "Escritorio Costa",
    imagen: "img/Kit de imágenes/escritorio_costa.png",
    descripcion: "Escritorio compacto con cajón organizado y tapa pasacables integrada en bambú laminado. Ideal para espacios de trabajo en casa, combina funcionalidad moderna con estética minimalista y sostenible, perfecto para el trabajo remoto.",
    medidas: "120 × 60 × 75 cm",
    materiales: "Bambú laminado, herrajes ocultos",
    acabado: "Laca mate resistente",
    almacenamiento: "1 cajon con organizador",
    cables: "Pasacables integrado",
  },
  {
    id:11,
    nombre: "Silla de Trabajo Belgrano",
    imagen: "img/Kit de imágenes/silla_trabajo_belgrano.png", 
    descripcion: "Silla ergonómica regulable en altura con respaldo de malla transpirable y asiento tapizado en tejido reciclado. Diseñada para largas jornadas de trabajo con máximo confort y apoyo lumbar, ideal para oficinas en casa y espacios de coworking.",
    medidas: "60 × 60 × 90-100 cm",
    materiales: "Malla técnica, tejido reciclado",
    acabado: "Base cromada, tapizado premium",
    Regulación: "Altura + inclinación respaldo",
    Certificación : "Ergonomía europea EN 1335",
  },
];